name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: "JDK ${{ matrix.java }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v3.1.0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: build with type checking
      run: ./gradlew --console=plain assemble
      working-directory: ./Java

